# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags: ['*']
  pull_request:

env:
  RELEASE_FILENAME: Ru.AenSidhe.RuCenterApi.${{ github.ref_name }}
  RELEASE_DIR: Ru.AenSidhe.RuCenterApi.Acme/bin/Release/net7.0/linux-musl-x64/publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore & Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Publish
      if: ${{ success() && github.ref_type == 'tag' }}
      run: dotnet publish -c Release --no-build --verbosity normal

    - name: Publish to artifacts
      if: ${{ success() && github.ref_type == 'tag' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.RELEASE_FILENAME }}
        path: ${{ env.RELEASE_DIR }}

    - name: Zip Release
      if: ${{ success() && github.ref_type == 'tag' }}
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: ${{ env.RELEASE_FILENAME }}
        directory: ${{ env.RELEASE_DIR }}


    - name: Upload files to a GitHub release
      if: ${{ success() && github.ref_type == 'tag' }}
      uses: svenstaro/upload-release-action@2.7.0
      with:
        file: ${{ env.RELEASE_DIR }}/${{ env.RELEASE_FILENAME }}
